Add support for test mode in (fire) sensor
Kane610/deconz pull request #188
Opened 2021-11-25 09:14 UTC by madwizard-thomas

Adds support for test mode for sensors. Deconz currently supports this for develco/frient smoke alarms such as the SMSZB-120. The flag (test mode IAS zone status) is set when a network test is performed (~6 second press on the smoke alarm test button) and the only way to detect a network test because the actual fire state flag is not changed when performing a test.

2021-11-25 20:57 UTC, Kane610 requested changes
First of all, thank you for contributing!

I'm thinking if this is only related to smoke alarms, maybe this fits better in the fire sensor class? Test buttons typically exist with smoke detectors but not with many of the other sensor types.

2021-11-25 21:38 UTC, madwizard-thomas commented
I was wondering the same thing but since I didn’t see any fire sensor specific fields yet I put it in the generic sensor class.
I’ll update the pull request!

2021-11-30 18:43 UTC, Kane610 approved these changes
Looks good, make sure all checks pass

2021-12-04 21:23 UTC, Kane610 reviewed
The only thing I'm thinking about is if the test property should be called in_test_mode or similar, since I've moved most properties to be more self explanatory, what do you think?

2021-12-09 09:03 UTC, madwizard-thomas commented
That would be fine by me, the spec calls the flag 'Sensor is in test mode' so `in_test_mode` would be appropriate.

2021-12-29 10:43 UTC, Kane610 commented
Sorry for delayed reply. Yes please change it to the more descriptive naming and you're done

2022-01-14 21:05 UTC, valentingc commented
@madwizard-thomas Thanks a lot for your work! I'd really much appreciate this feature getting merged soon - since it has been a while since your last commit, I was wondering whether I could help you out to finish your PR, as it is so close to being completed.

@Kane610 
I've renamed the property in my fork: https://github.com/valentingc/deconz/commit/b5292b93bbc571c8425ae1a956c551ad8adc126e
Would that fit your renaming requirement as discussed above?
I adapted the tests as well, they are running through.

@madwizard-thomas Plese let me know whether you are able to finish this PR anytime soon. I can open a PR in your fork so that you can easily integrate it into this open PR, you can of course also implement it by yourself, or I could also open a new PR here in @Kane610's repo if this makes anything easier - just let me know if I can be of any help.

Thanks a lot to both of you!

2022-01-15 09:45 UTC, Kane610 commented
@valentingc yes looks good, lets just change so the default value for get("test") returns a False bool and make the method return type be strict bool. Then we can merge this

2022-01-16 11:49 UTC, valentingc commented
@Kane610  done - let's continue in the new PR so that you can merge this: https://github.com/Kane610/deconz/pull/193 - Thanks a lot for your support, very much appreciated!

2022-01-18 18:33 UTC, Kane610 commented
Thank you both!

2022-01-18 18:33 UTC, closed without merging

2022-01-24 22:30 UTC, Kane610 commented
PR is up https://github.com/home-assistant/core/pull/64873